services:
  database:
    container_name: database
    ports:
      - 5432:5432
    image: postgres:16.0-alpine3.18
    env_file:
      - ../.env.development
  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher"
    ports:
      - "1025:1025"
      - "1080:1080"
